on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/ml-verse
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: run test from R
        run: Rscript test_python_R.R
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
